name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-typecheck-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      
      - name: install dependencies
        run: pnpm install

      - name: linter
        run: pnpm run lint
      
      - name: typechecker
        run: pnpm exec tsc --noEmit

      - name: build
        run: pnpm run build
